config/routes.rb
Rails.application.routes.draw do
  
  resources :announcements, only: [:index, :show]
  resources :banners, only: [:index, :show]

  devise_for :admins
  
  root "statics#index"
  
  get "/ebike/index.php" => redirect("http://ebike.citypower.com.tw/regist.php")

  resources :pages, :controller => :statics, only: [:index, :show, :vehicles] do 
    collection do
      get "vehicles" => "statics#vehicles", :as => "vehicles"
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :vehicles, only: [:index, :show]
  
  resources :stations, only: [:index, :show] do 
    collection do 
      post 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stations#fetch_from_country'
  get 'fetch_from_city' => 'stations#fetch_from_city'

  resources :contacts, only: [:index, :create]
  # resources :reservations, only: [:index, :create]

  resources :FAQs, :controller => :boxes , :only => [ :index, :show] # resources :boxes, only: [:index, :show]
  
  resources :faqs, only: [:fetch_by_box] do
    collection do 
      match 'search' => 'faqs#search', via: [:post], as: :search  
    end
    member do
      get 'fetch_by_box', action: 'fetch_by_box'
    end
  end

  # Admin
  namespace :admin do

    authenticated :admin do
      root "announcements#index"#, :as => :authenticated_root
    end
    
    resources :admins

    resources :announcements do 
      member do
        post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
        match :announcementphoto_upload, :via => :get

        get '/custom_edit' => 'announcements#custom_edit'
        patch '/custom_edit' => 'announcements#update'

      end
    end
    
    resources :index_sliders, controller: 'banners', type: 'IndexSlider'
    resources :selected_vehicles, controller: 'banners', type: 'SelectedVehicle'
    
    #BES Stations
    resources :stations do
      member do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'

        post 'create_station_attachment' , :action => 'create_station_attachment'
        match :stationphoto_upload, :via => :get
      end 

      collection do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'
      end
    end

    resources :categories do 
      resources :vehicles do

        get   '/sliders'       => 'vehicles#slider', as: 'slider'
        patch  '/upload_slider'       => 'vehicles#upload_slider'

        get   '/dms'       => 'vehicles#dm', as: 'dm'
        patch  '/upload_dm'       => 'vehicles#upload_dm'

        get   '/photos'       => 'vehicles#photo', as: 'photo'
        patch  '/upload_photo'       => 'vehicles#upload_photo'

        resources :specs
        resources :accessories
        resources :features
        resources :colors

      end

      member do
        patch 'reorder' , :action => 'reorder'
      end 

    end

    resources :vehicles do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end
    
    resources :boxes do 
      resources :faqs do 
        member do 
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        end
      end 
    end

    resources :galleries do 
      member do
        patch 'multiple_reorder' , :action => 'multiple_reorder'
      end 
    end

    resources :contacts, :only => [:index, :update, :reset_status] do
      collection do 
        get 'history', action: 'history'
      end
      member do 
        put 'reset_status', action: 'reset_status'
        put 'soft_delete', action: 'soft_delete'
      end
    end
    
    resources :reservations, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end
    
  end

  get '(*url)'   => 'errors#index'

end

app/models/box.rb
#encoding: utf-8
class Box < ActiveRecord::Base
  has_many :faqs, dependent: :destroy

  belongs_to :daddy, :class_name => "Box", :foreign_key => 'parent_id' 
  has_many :children,  :class_name => "Box", :foreign_key => 'parent_id'

  scope :for_admin, -> { where( "parent_id != 0" ) }
  scope :without_root_node, -> { where( "parent_id != 0 AND depth = 1" ) }

  def self.return_root_node
    return Box.find_by('parent_id=0')
  end

  def self.get_level_hierarchy()
    
    if Rails.env.production?
      sql = "SELECT boxes.id, boxes.depth, boxes.parent_id, boxes.name FROM boxes WHERE  boxes.parent_id != 0 "
    else
      #local
      sql = "SELECT boxes.id, boxes.depth, boxes.parent_id, boxes.name FROM boxes WHERE boxes.parent_id != 0 "
    end

    return records_array = ActiveRecord::Base.connection.execute(sql)

  end

  #should be useful to create breadcrum
  def find_my_direct_parent
    
     self.findpapa
     directparents = @@directparent.dup
     @@directparent.clear
     
     return directparents
     
  end
  
  #find direct parent levle mainly for breadcrumb
  @@directparent = []
  def findpapa

    if self.parent_id == 0
        @@directparent << self
       return @@directparent
    end   
    
    if self.parent_id > 0  
        @@directparent << self
        daddy.findpapa
    end
    
  end

  def delete_children
    Box.destroy_all(id: self.descendents)
  end

  def descendents
    #children.preload(:parent).each do |child|  child.descendents end
   children.each do |child|
      [child] + child.descendents
    end
  end


end

app/controllers/admin/boxes_controller.rb
#encoding: utf-8
class Admin::BoxesController < AdminController
  before_action :set_box, only: [:update ,:destroy]

  def index
    @box = Box.new
    @boxes = Box.for_admin.where("depth = 1")
  end

  def show
    @box = Box.includes(:faqs).find(params[:id])
    @boxes = Box.where("parent_id = #{@box.id}")
    @new_box = Box.new
    @breadcrumb = @box.find_my_direct_parent
  end

  def create

    @box = Box.new(box_params)
    @box.save

    # if params[:filename].present? 
    #   display_name = params[:filename]
    # else 
    #   display_name = "#{@box.name}-CATEGORY-#{@box.galleries.count + 1}"
    # end
      
    # @latestAttach = BoxCoverGallery.create(:attachment => params[:attachment], :attachable => @box, :file_name => display_name) if params[:attachment]


    respond_to do |format|
      format.html { redirect_to :back }
    end
  end

  def update

    # if params[:filename].present? 
    #   display_name = params[:filename]
    # else 
    #   display_name = "#{@box.name}-CATEGORY-#{@box.galleries.count + 1}"
    # end
      
    # @latestAttach = BoxCoverGallery.create(:attachment => params[:attachment], :attachable => @box, :file_name => display_name) if params[:attachment]
    
    @box.update_attributes(box_params) if @box

    redirect_to :back
  end

  def destroy

    #@box.destroy if @box && @box.faqs.count == 0
    deletable = true
    if @box.faqs.count > 0
      flash[:alert] = "此分類下仍有項目 無法刪除" 
      deletable = false
    end
    
    # prevent delete by mistake
    Box.where(id: @box.descendents).each do |box|
      if box.faqs.count > 0
        flash[:alert] = "分類 [#{box.name}] 下仍有項目 無法刪除"
        deletable = false
        break
      end
    end
    
    @box.destroy if deletable == true
    
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:name, :parent_id, :depth, :attachment)
    end

end

app/controllers/boxes_controller.rb
#encoding: utf-8
class BoxesController < ApplicationController
  # before_action :set_faq, only: [:show]
  
  def index
    @boxes = Box.without_root_node
    @box = @boxes.first
    @faqs = @box.faqs
  end

  def show 
    @boxes = Box.without_root_node
    @box = Box.includes(:faqs).find_by_id(params[:id])
    @faqs = @box.faqs if @box

    respond_to do |format|
      if(@box)
        #@content = @faq.article.content
        format.html
      else
        format.html { redirect_to FAQs_path(), alert: "找不到項目" }
      end
    end

  end

  def fetch_by_box
    @faq = Faq.find_by_id(params[:id])
    respond_to do |format|
      if(@faq)
        #@content = @faq.article.content
        format.js
      else
        format.html { redirect_to FAQs_path(), alert: "找不到項目" }
      end
    end
    
  end

  private
    
    # def set_faq
    #   @faq = Faq.find_by_id(params[:id])
    # end

end

app/views/admin/boxes/index.html.erb
<header>
  <h2 class="left">常見問題</h2>        
</header>
<article>
  <div class="hgroup">
    <h3 class="left">分類列表</h3>
    <div class="button right">
      <a href="javascript:void(0);" class="right highlight toggle_new_box">新增分類<img src="/images/admin/add_folder.png"></a>
    </div>
  </div>
  <div class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      
      <% @boxes.each do |box| %>

        <tr class="show_box_<%= box.id %>" >
          <td width="6%" class="icon">
            <img src="/images/admin/folder.png">
          </td>
          <td width="76%">
            <%= link_to(box.name, admin_box_path(box)) %>
          </td>
          <td width="18%">
            <div class="tool">
              <%= link_to "", "javascript:void(0);", :data => { :id => box.id }, :class => "edit", title:"編輯" %><%= link_to "", admin_box_path(box), :data => { :confirm => "將會刪除分類底下所有項目，確定繼續？" }, :method => :delete, :class => "delete", title: "刪除" %>
            </div>
          </td>
        </tr>

        
        
        <tr class="list-edit edit_box_<%= box.id %>" style="display:none">
          <%= form_for(box, :url => admin_box_path(box) , html: { id: "patchthisbox_#{box.id}", :multipart => true }) do |f| %>
          
          <td width="6%" class="icon">
            <img src="/images/admin/folder.png">
          </td>
          <td width="76%">
            <%= f.text_field :name, class:"text", placeholder: "分類名稱", style:"width:50%" %>
          </td>          
          <td align="right" valign="top" width="18%">
            <div class="tool">
              <a href="javascript: document.getElementById('patchthisbox_<%= box.id %>').submit();" class="uvs" data-no-turbolink = true >儲存</a><%= link_to "取消", "javascript:void(0);" ,:data => { :id => box.id }, :class => "uvs" %>
            </div>
          </td>
          <% end %>
        </tr>

      <% end %>
    <!-- new -->

    <tr class="list-new list-edit edit_box" style="display:none;">
    <%= form_for(@box, :url => admin_boxes_path , html: {id: "create_new_box", :multipart => true }) do |f| %>
    <td width="6%" class="icon">
      <img src="/images/admin/folder.png">
    </td>
    <td width="76%">

      <%= f.text_field :name, :placeholder => "分類名稱" , class: "text new_box_name_input" ,placeholder:"分類名稱" %>

      <%= f.hidden_field :parent_id, value: 1 %>
      <%= f.hidden_field :depth, value: 1 %>
      
    </td>
    <td align="right" width="18%">
      <div class="tool">
        <a href="javascript: document.getElementById('create_new_box').submit();" class="uvs" data-no-turbolink = true >儲存</a><%= link_to("取消", "javascript:void(0);", :class => "uvs cancel_new_box") %>
      </div>
    </td>
    <% end %>
  </tr>

    </table>
  </div>
</article>



<script type="text/javascript">
$(document).ready(function(){
  $(".toggle_new_box").click(function(){

    if($("tr[class*=edit_box]:visible").length > 0){
      alert("請先完成編輯中的分類");
    }
    else{
      
      $(".list-new").toggle();
    }
  });

  $(".cancel_new_box").click(function(){
      $(".new_box_name_input").val(''); //clear input
      $(".list-new").toggle();
  });

  $(".edit").click(function(){
    $active_id = $(this).data("id");
    if($("tr[class*=edit_box]:visible").length > 0){
      alert("請先完成編輯中的分類");
    }
    else{
      toggle_edit_area($active_id);
    }
  });

  $(".uvs").click(function(){
    $active_id = $(this).data("id");
    toggle_edit_area($active_id);
  });

  function toggle_edit_area(active_id){
    $("tr.edit_box_" + active_id).toggle();
    $("tr.show_box_" + active_id).toggle();
  }
});
</script>

app/views/admin/boxes/show.html.erb
<header>
  <h2 class="left">常見問題</h2>        
</header>

<article>

  <% if @box.depth < 1 %>

    <div class="hgroup">
      <h3 class="left">
        <% @breadcrumb.each_with_index do | bread, index | %>
          <%= bread.name if index == 0 %>
            <% if index >= 1  %>
              <span>/<%= bread.name %></span>
              <!-- link_to  ancestor.name,  admin_hqlevel_path(ancestor.id, :locale => I18n.locale) -->
            <% end %>

            <% if index == (@breadcrumb.count - 1 ) %>
              <!-- <span>/分類列表</span> -->
            <% end %>
        <% end %>
      </h3>
      <div class="button right">
        <a href="javascript:void(0);" class="right highlight toggle_new_box">新增分類<img src="/images/admin/add_folder.png"></a>
      </div>
    </div>
    <div class="list">
    
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        
        <% @boxes.each do |box| %>

          
          <tr class="show_box_<%= box.id %>" >
            <td width="6%" class="icon">
              <img src="/images/admin/folder.png">
            </td>
            <td width="76%">
              <%= link_to(box.name, admin_box_path(box)) %>
            </td>
            <td width="18%">
              <div class="tool">
                <%= link_to "", "javascript:void(0);", :data => { :id => box.id }, :class => "edit", title:"編輯" %><%= link_to "", admin_box_path(box), :data => { :confirm => "將會刪除分類底下所有FAQ，確定繼續？" }, :method => :delete, :class => "delete", title: "刪除" %>
              </div>
            </td>
          </tr>

          
          
          <tr class="list-edit edit_box_<%= box.id %>" style="display:none;">
            <%= form_for(box, :url => admin_box_path(box) , html: { id: "patchthisbox_#{box.id}"}) do |f| %>
            
            <td width="6%" class="icon">
              <img src="/images/admin/folder.png">
            </td>
            <td width="76%">
              
              <%= f.text_field :name, class:"text", placeholder: "分類名稱", style:"width:50%" %>
              
            </td>
            
            <td align="right" valign="top" width="18%">
              <div class="tool">
                <a href="javascript: document.getElementById('patchthisbox_<%= box.id %>').submit();" class="uvs" data-no-turbolink = true >儲存</a><%= link_to "取消", "javascript:void(0);" ,:data => { :id => box.id }, :class => "uvs" %>
              </div>
            </td>
            <% end %>
          </tr>

        <% end %>

      <!-- new -->
        <tr class="list-new list-edit edit_box" style="display:none;">
          <%= form_for(@new_box, :url => admin_boxes_path , html: {id: "create_new_box" }) do |f| %>
            <td width="6%" class="icon">
              <img src="/images/admin/folder.png">
            </td>
            <td width="76%">
              
                <%= f.text_field :name, :placeholder => "分類名稱" , class: "text new_box_name_input" %>

                <%= f.hidden_field :parent_id, value: "#{@box.id}" %>
                <%= f.hidden_field :depth, value: "#{@box.depth + 1}" %>
              
            </td>
            <td width="18%" align="right">
              <div class="tool">
                <a href="javascript: document.getElementById('create_new_box').submit();" class="uvs" data-no-turbolink = true >儲存</a><%= link_to("取消", "javascript:void(0);", :class => "uvs cancel_new_box") %>
              </div>
            </td>
          <% end %>
        </tr>

      </table>
    </div>

    <div class="button">
      <a href="<%= admin_boxes_path %>" class="left">
        <img src="/images/admin/left.png">返回
      </a>
    </div>

  <% else %>

    <div class="hgroup">
      <h3 class="left">
        <% @breadcrumb.each_with_index do | bread, index | %>
          <%= bread.name if index == 0 %>

          <% if index >= 1  %>
            <span>/<%= bread.name %></span>
            <!-- link_to  ancestor.name,  admin_hqlevel_path(ancestor.id, :locale => I18n.locale) -->
          <% end %>

          <% if index == (@breadcrumb.count - 1 ) %>
            <!-- <span>/分類列表</span> -->
          <% end %>
        <% end %>
      </h3>
      <div class="button right">
        <%= link_to  admin_box_faqs_path(@box), :method => :post, class: "right highlight toggle_new_box" do %>
          新增項目<img src="/images/admin/add_folder.png">
        <% end %>
      </div>
    </div>
    <div class="list">      
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <% @box.faqs.each do |faq| %>

        <tr>
          <td width="6%" class="icon"><img src="/images/admin/li.png"></td>
          <td width="76%">
            <%= link_to(faq.question, edit_admin_box_faq_path(@box, faq)) %>
          </td>
          <td width="18%">
            <div class="tool">
              <%= link_to "", edit_admin_box_faq_path(@box, faq), class: 'edit' %><%= link_to "", admin_box_faq_path(@box, faq), :method => :delete, :data => {:confirm => "確定刪除？"}, class: 'delete' %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>

    </div>
    <div class="button">
      <a href="<%= admin_boxes_path %>" class="left">
        <img src="/images/admin/left.png">返回
      </a>
    </div>
  <% end %>
    
  </div>
  
</article>

<script type="text/javascript">
$(document).ready(function(){
  $(".toggle_new_box").click(function(){

    if($("tr[class*=edit_box]:visible").length > 0){
      alert("請先完成編輯中的產品分類");
    }
    else{
      
      $(".list-new").toggle();
    }
  });

  $(".cancel_new_box").click(function(){
      $(".new_box_name_input").val(''); //clear input
      $(".list-new").toggle();
  });

  $(".edit").click(function(){
    $active_id = $(this).data("id");
    if($("tr[class*=edit_box]:visible").length > 0){
      alert("請先完成編輯中的產品分類");
    }
    else{
      toggle_edit_area($active_id);
    }
  });

  $(".uvs").click(function(){
    $active_id = $(this).data("id");
    toggle_edit_area($active_id);
  });

  function toggle_edit_area(active_id){
    $("tr.edit_box_" + active_id).toggle();
    $("tr.show_box_" + active_id).toggle();
  }
});
</script>