config/routes.rb
Rails.application.routes.draw do
  
  resources :announcements, only: [:index, :show]
  resources :banners, only: [:index, :show]

  devise_for :admins
  
  root "statics#index"
  
  get "/ebike/index.php" => redirect("http://ebike.citypower.com.tw/regist.php")

  resources :pages, :controller => :statics, only: [:index, :show, :vehicles] do 
    collection do
      get "vehicles" => "statics#vehicles", :as => "vehicles"
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :vehicles, only: [:index, :show]
  
  resources :stations, only: [:index, :show] do 
    collection do 
      post 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stations#fetch_from_country'
  get 'fetch_from_city' => 'stations#fetch_from_city'

  resources :contacts, only: [:index, :create]
  # resources :reservations, only: [:index, :create]

  resources :FAQs, :controller => :boxes , :only => [ :index, :show] # resources :boxes, only: [:index, :show]
  
  resources :faqs, only: [:fetch_by_box] do
    collection do 
      match 'search' => 'faqs#search', via: [:post], as: :search  
    end
    member do
      get 'fetch_by_box', action: 'fetch_by_box'
    end
  end

  # Admin
  namespace :admin do

    authenticated :admin do
      root "announcements#index"#, :as => :authenticated_root
    end
    
    resources :admins

    resources :announcements do 
      member do
        post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
        match :announcementphoto_upload, :via => :get

        get '/custom_edit' => 'announcements#custom_edit'
        patch '/custom_edit' => 'announcements#update'

      end
    end
    
    resources :index_sliders, controller: 'banners', type: 'IndexSlider'
    resources :selected_vehicles, controller: 'banners', type: 'SelectedVehicle'
    
    #BES Stations
    resources :stations do
      member do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'

        post 'create_station_attachment' , :action => 'create_station_attachment'
        match :stationphoto_upload, :via => :get
      end 

      collection do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'
      end
    end

    resources :categories do 
      resources :vehicles do

        get   '/sliders'       => 'vehicles#slider', as: 'slider'
        patch  '/upload_slider'       => 'vehicles#upload_slider'

        get   '/dms'       => 'vehicles#dm', as: 'dm'
        patch  '/upload_dm'       => 'vehicles#upload_dm'

        get   '/photos'       => 'vehicles#photo', as: 'photo'
        patch  '/upload_photo'       => 'vehicles#upload_photo'

        resources :specs
        resources :accessories
        resources :features
        resources :colors

      end

      member do
        patch 'reorder' , :action => 'reorder'
      end 

    end

    resources :vehicles do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end
    
    resources :boxes do 
      resources :faqs do 
        member do 
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        end
      end 
    end

    resources :galleries do 
      member do
        patch 'multiple_reorder' , :action => 'multiple_reorder'
      end 
    end

    resources :contacts, :only => [:index, :update, :reset_status] do
      collection do 
        get 'history', action: 'history'
      end
      member do 
        put 'reset_status', action: 'reset_status'
        put 'soft_delete', action: 'soft_delete'
      end
    end
    
    resources :reservations, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end
    
  end

  get '(*url)'   => 'errors#index'

end

app/models/vehicle.rb
#encoding: utf-8
class Vehicle < ActiveRecord::Base

  belongs_to :category
  
  has_many :specs, dependent: :destroy
  has_many :features, dependent: :destroy
  has_many :colors, dependent: :destroy
  has_many :accessories, dependent: :destroy

  has_many :galleries, -> { order('ranking, created_at') } , as: :attachable , dependent: :destroy

  #before_destroy { |record| Banner.destroy_all "related_vehicle_id = #{record.id}"  }
  default_scope { order(:ranking) }
  scope :front_show_by_cate, ->(category_id) { where("category_id = ? AND status = ?", category_id, "enable") }

  store :context, accessors: [ :context_1, :context_2, :context_3 ]

  before_validation :check_attrs
  #callback
  after_create :create_default_specs
  after_destroy :destroy_selected_vehicles_in_banner

  validates_presence_of :name, :title_color #, :cf

  private

  def check_attrs
    self.name = "未命名車款" if self.name.blank?
    self.status = "enable" if self.status.blank?
    self.title_color = "000000" if self.title_color.blank?
    # self.cf = "<iframe>...</iframe>" if self.cf.blank?
  end

  def create_default_specs
    
    #k-v pair: title:context
    @default_specs = [
      {title: '電機型式', context: ''},
      {title: '電機瓦數', context: ''},
      {title: '制動系統', context: ''},
      {title: '懸吊系統', context: ''},
      {title: '電池容量', context: ''},
      {title: '電池組數', context: ''},
      {title: '最高時速', context: ''},
      {title: '經濟速度', context: ''},
      {title: '里程'   , context: ''},
      {title: '爬坡效能', context: ''},
      {title: '檔位變換', context: ''}
    ]

    @default_specs.each do | spec |
      spec.reverse_merge!(vehicle_id: self.id )
    end     
    
    Spec.create(@default_specs)

  end

  def destroy_selected_vehicles_in_banner
    Banner.where(type: 'SelectedVehicle', related_product_id: self.id).destroy_all
  end

end

app/controllers/admin/vehicles_controller.rb
 #encoding: utf-8
class Admin::VehiclesController < AdminController
  
  before_action :set_vehicle_with_category, only: [:create, :show]
  before_action :set_vehicle, only: [:edit,:update,:destroy]
  #before_action :get_vehicle_cate, only: [:create]
  
  def show
    @com_accessories = @vehicle.accessories.where(type: 'ComplimentaryAccessory').includes(:galleries)
    @opt_accessories = @vehicle.accessories.where(type: 'OptionalAccessory').includes(:galleries)
    @features = @vehicle.features.includes(:galleries)
    @colors = @vehicle.colors.includes(:galleries)
    @cover = @vehicle.galleries.where(type: 'VehicleCover')
    @sliders = @vehicle.galleries.where(type: 'VehicleSlider') 
    @photos = @vehicle.galleries.where(type: 'VehiclePhotoGallery')
    @dms = @vehicle.galleries.where(type: 'VehicleDMFile')
  end

  def create

    @vehicle = Vehicle.create()

    @category = Category.find_by_id(params[:category_id])
    @category.vehicles << @vehicle

    respond_to do |format|
      if( @vehicle.errors.any? )
        format.html { redirect_to :back, alert: "新增失敗" }
      else
        format.html { redirect_to edit_admin_category_vehicle_path(@category, @vehicle) }
      end
    end
  end

  def edit
    @gallery_count = @vehicle.galleries.select{ |v| v['type'] == "VehicleCover" }.count
  end

  def slider
    @vehicle = Vehicle.find_by_id(params[:vehicle_id])
    @gallery_count = @vehicle.galleries.select{ |v| v['type'] == "VehicleSlider" }.count
  end

  def upload_slider
    @vehicle = Vehicle.find_by_id(params[:vehicle_id])
    #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@vehicle.name}-vehicle-#{@vehicle.galleries.count + 1}"
    end
    @latestAttach = VehicleSlider.create(:attachment => params[:attachment], :attachable => @vehicle, :file_name => display_name) if params[:attachment]

    @vehicle.update(vehicle_params) 
    
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to :back, notice: '更新成功' }
      else
        format.html { render :back, notice: @vehicle.errors.full_messages }
      end      
    end

  end

  def dm
    @vehicle = Vehicle.find_by_id(params[:vehicle_id])
    @gallery_count = @vehicle.galleries.select{ |v| v['type'] == "VehicleDMFile" }.count
  end

  def upload_dm
    @vehicle = Vehicle.find_by_id(params[:vehicle_id])
    #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@vehicle.name}-vehicle-#{@vehicle.galleries.count + 1}"
    end
    @latestAttach = VehicleDMFile.create(:attachment => params[:attachment], :attachable => @vehicle, :file_name => display_name) if params[:attachment]

    @vehicle.update(vehicle_params) 
    
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to :back, notice: '更新成功' }
      else
        format.html { render :back, notice: @vehicle.errors.full_messages }
      end      
    end
  end

  def photo
    @vehicle = Vehicle.find_by_id(params[:vehicle_id])
    @gallery_count = @vehicle.galleries.select{ |v| v['type'] == "VehiclePhotoGallery" }.count
  end

  def upload_photo
    @vehicle = Vehicle.find_by_id(params[:vehicle_id])
    #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@vehicle.name}-vehicle-#{@vehicle.galleries.count + 1}"
    end
    @latestAttach = VehiclePhotoGallery.create(:attachment => params[:attachment], :attachable => @vehicle, :file_name => display_name) if params[:attachment]

    @vehicle.update(vehicle_params) 
    
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to :back, notice: '更新成功' }
      else
        format.html { render :back, notice: @vehicle.errors.full_messages }
      end      
    end
  end
  
  def update

    #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@vehicle.name}-vehicle-#{@vehicle.galleries.count + 1}"
    end
    @latestAttach = VehicleCover.create(:attachment => params[:attachment], :attachable => @vehicle, :file_name => display_name) if params[:attachment]

    @vehicle.update(vehicle_params.merge({:status => "enable"})) 
    
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to :back, notice: '更新成功' }
        #format.html { redirect_to admin_product_cate_product_path(@vehicle.product_cate_id, @vehicle) }
      else
        format.html { render :edit, notice: @vehicle.errors.full_messages }
      end      
    end

  end

  def reorder
    errorFlag = false
    params[:vehicles][:reorderset].each_with_index do | id , index |
      the_id = Vehicle.find(id)
      if !the_id.nil?
        the_id.update_attribute(:ranking , index+1 )
      else
        errorFlag = true
      end
    end

    respond_to do |format|
      if errorFlag
        format.json { head :no_content }
      else
        # flash[:notice] = "重新排序成功"
        format.json do render json: flash end
      end
    end

  end  

  def destroy
    
    @vehicle.destroy
    
    redirect_to :back
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find_by_id(params[:id])
  end

  def set_vehicle_with_category
    @vehicle = Vehicle.includes(:category).find_by_id(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:name, :price, :price_for_sale, :intro,:context_1, :context_2, :context_3, :attachment, :status, :cf, :description, :title_color)
  end

end
 

app/controllers/vehicles_controller.rb
#encoding: utf-8
class VehiclesController < ApplicationController

  def show
  
    @vehicle = Vehicle.where(status: 'enable').includes(:galleries, :colors, :features, :specs, :accessories).find_by_id(params[:id])

    if @vehicle
      @features = @vehicle.features.includes(:galleries)
      @com_accessories = @vehicle.accessories.where(type:'ComplimentaryAccessory').includes(:galleries)
      @opt_accessories = @vehicle.accessories.where(type:'OptionalAccessory').includes(:galleries)
    else
      redirect_to vehicles_pages_path
    end

  end

end

app/views/admin/vehicles/dm.html.erb
<header>
  <h2 class="left">車款介紹</h2>
  <nav class="left">
    <%= link_to "簡介", edit_admin_category_vehicle_path(@vehicle.category, @vehicle) %>
    <%= link_to "輪播", admin_category_vehicle_slider_path(@vehicle.category, @vehicle) %>
    <%= link_to "車色", admin_category_vehicle_colors_path(@vehicle.category, @vehicle) %>
    <%= link_to "特色", admin_category_vehicle_features_path(@vehicle.category, @vehicle) %>
    <%= link_to "規格", admin_category_vehicle_specs_path(@vehicle.category, @vehicle) %>
    <%= link_to "配件", admin_category_vehicle_accessories_path(@vehicle.category, @vehicle)%>
    <%= link_to "型錄", admin_category_vehicle_dm_path(@vehicle.category, @vehicle), class: 'active' %>
    <%= link_to "其他", admin_category_vehicle_photo_path(@vehicle.category, @vehicle)%>
  </nav>
</header>

<article>

<%= render 'admin/common/show_document_by_type', target: @vehicle, target_title: '附件', type: 'VehicleDMFile' %>

<% if @gallery_count < 1 %>

  <%= simple_form_for(@vehicle, :url => admin_category_vehicle_upload_dm_path(params[:category_id] , @vehicle), html: { id: "patchthisvehicle", :multipart => true } ) do |f| %>

    <%= render 'admin/common/upload_document_by_type', target_title: '附件' %>
    
    <%= f.hidden_field :status, :value => 'enable' %>

    <div class="button"> 
      <%= f.submit '上傳', class: 'highlight right'  %>
    </div>
  <% end %>

<% end %>
 
</article>

app/views/admin/vehicles/edit.html.erb
<script type="text/javascript" src="/js_plugins/jscolor/jscolor.js"></script>

<header>
  <h2 class="left">車款介紹</h2>
  <nav class="left">
    <%= link_to "簡介", edit_admin_category_vehicle_path(@vehicle.category, @vehicle), class: 'active' %>
    <%= link_to "輪播", admin_category_vehicle_slider_path(@vehicle.category, @vehicle)%>
    <%= link_to "車色", admin_category_vehicle_colors_path(@vehicle.category, @vehicle)%>
    <%= link_to "特色", admin_category_vehicle_features_path(@vehicle.category, @vehicle)%>
    <%= link_to "規格", admin_category_vehicle_specs_path(@vehicle.category, @vehicle)%>
    <%= link_to "配件", admin_category_vehicle_accessories_path(@vehicle.category, @vehicle)%>
    <%= link_to "型錄", admin_category_vehicle_dm_path(@vehicle.category, @vehicle)%>
    <%= link_to "其他", admin_category_vehicle_photo_path(@vehicle.category, @vehicle)%>
  </nav>
  <div class="explain right"><p>圖片尺寸：330 * 400</p></div>
</header>

<article>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
  
    <%= simple_form_for(@vehicle, :url => admin_category_vehicle_path(params[:category_id] , @vehicle), html: { id: "patchthisvehicle", :multipart => true } ) do |f| %>  

    <% if @gallery_count > 0 %>
      <%= render 'admin/common/show_by_type', target: @vehicle, target_title: '封面', type: 'VehicleCover' %>
    <% else %>
      <%= render 'admin/common/upload_by_type', target_title: '封面' %>
    <% end %>

    <div class='form'>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
       <tr>
          <td width="9%">名稱：</td>
          <td width="39%">
            <%= f.input_field :name, required: true , class: 'text' %>
          </td>
          <td width="4%">&nbsp;</td>
          <!-- <td width="9%">顏色：</td> -->
          <td width="9%"></td>
          <td width="39%">
            <%# f.input_field :title_color, class: 'color text', required: true %>
          </td>           
        </tr>
        <tr>
          <td valign="top">描述：</td>
          <td colspan="4">
            <%= f.text_area :description %>
          </td>
        </tr>
         <tr>
          <td valign="top">CF：</td>
          <td colspan="4">
            <%= f.text_area :cf %>
          </td>
        </tr>
      </table>   
    </div>

    <div class="button"> 
      <%= link_to admin_category_path(@vehicle.category) , class: 'left' do %>
        <img src="/images/admin/left.png">返回
      <% end %>
      <%= f.submit '儲存', class: 'highlight right' %>
    </div>

  <% end %>

</article>



<script type="text/javascript">
$(document).ready(function(){

    
});
</script>

app/views/admin/vehicles/photo.html.erb
<header>
  <h2 class="left">車款介紹</h2>
  <nav class="left">
    <%= link_to "簡介", edit_admin_category_vehicle_path(@vehicle.category, @vehicle) %>
    <%= link_to "輪播", admin_category_vehicle_slider_path(@vehicle.category, @vehicle)%>
    <%= link_to "車色", admin_category_vehicle_colors_path(@vehicle.category, @vehicle)%>
    <%= link_to "特色", admin_category_vehicle_features_path(@vehicle.category, @vehicle)%>
    <%= link_to "規格", admin_category_vehicle_specs_path(@vehicle.category, @vehicle)%>
    <%= link_to "配件", admin_category_vehicle_accessories_path(@vehicle.category, @vehicle)%>
    <%= link_to "型錄", admin_category_vehicle_dm_path(@vehicle.category, @vehicle)%>
    <%= link_to "其他", admin_category_vehicle_photo_path(@vehicle.category, @vehicle), class: 'active'%>
  </nav>
</header>
<article>
  
  
  <%= simple_form_for(@vehicle, :url => admin_category_vehicle_upload_photo_path(params[:category_id] , @vehicle), html: { id: "patchthisvehicle", :multipart => true } ) do |f| %>

    <%= render 'admin/common/upload_by_type', target_title: '圖片' %>
    
    <%= f.hidden_field :status, :value => 'enable' %>
    <div class="button"> 
    <%= f.submit '上傳', class: 'highlight right' %>
    </div>

  <% end %>
  

  <div class="gallery">
    <%= render 'admin/common/show_by_type', target: @vehicle, target_title: '', type: 'VehiclePhotoGallery' %>
  </div>

</article>

app/views/admin/vehicles/show.html.erb
Vehicle  SHOW
<br>
= CF<br>
<%= @vehicle.cf.html_safe if @vehicle.cf %>
<br>
= DM DOWNLOAD<br>
<% @dms.each do |dm| %>
  <%= link_to "#{dm.file_name}", dm.attachment.url, target: '_blank' %>
<% end %>
<br>

= SPEC<br>
<% @vehicle.specs.each do |spec| %>
  <%= spec.title %> == <%= spec.context %> <br>
<% end %><br>

== COLORS<br>
<% @colors.each do |color| %>
  <%= color.name %> = 
  <div style='width:50px;height:50px;background:#<%= "#{color.hexcode}"%>;'>&nbsp;</div>
  
  <% color.galleries.each do |color_photo| %>
    <% if color_photo %>
      <%= image_tag color_photo.attachment.url %>
    <% end %>
  <% end %><br>

<% end %>
<br>

== FEATURES<br>
<% @features.each_with_index do |feature, index| %>
  +<%= feature.title %>+<br>
  <%= feature.context %><br>
  
  <% feature.galleries.each do |feature_photo| %>
    <% if feature_photo %>
      <%= image_tag feature_photo.attachment.url %>
    <% end %>
  <% end %><br>

  <%= "<br>".html_safe if (index+1)%3 == 0 %>
<% end %>
== sliders<br>
<% @sliders.each do |slider| %>
  <%= image_tag slider.attachment.url %>
<% end %>
<br>
== cover<br>
<% @cover.each do |cover| %>
  <%= image_tag cover.attachment.url %>
<% end %>
<br>
== accessory<br>
[標配]<br>
<% @com_accessories.each_with_index do |accessory, index| %>
  +(標配)<%= accessory.title %>+<br>
  <%= accessory.context %><br>
  
  <% accessory.galleries.each do |accessory_photo| %>
    <% if accessory_photo %>
      <%= image_tag accessory_photo.attachment.url %>
    <% end %>
  <% end %><br>

  <%= "<br>".html_safe if (index+1)%3 == 0 %>
<% end %>
[選配]<br>
<% @opt_accessories.each_with_index do |accessory, index| %>
  +(選配)<%= accessory.title %>+<br>
  <%= accessory.context %><br>
  
  <% accessory.galleries.each do |accessory_photo| %>
    <% if accessory_photo %>
      <%= image_tag accessory_photo.attachment.url %>
    <% end %>
  <% end %><br>

  <%= "<br>".html_safe if (index+1)%3 == 0 %>
<% end %>

<br>
== other images<br>
<% @photos.each_with_index do |photo, index| %>
  <%= image_tag photo.attachment.url %>
  <%= "<br>".html_safe if (index+1)%3 == 0 %>
<% end %>
<br>

app/views/admin/vehicles/slider.html.erb
= slider =
<header>
  <h2 class="left">編輯產品</h2>
  <nav class="left">
    <%= link_to "Basic", edit_admin_category_vehicle_path(@vehicle.category, @vehicle)%>
    <%= link_to "Specs", admin_category_vehicle_specs_path(@vehicle.category, @vehicle)%>
    <%= link_to "Features", admin_category_vehicle_features_path(@vehicle.category, @vehicle)%>
    <%= link_to "Colors", admin_category_vehicle_colors_path(@vehicle.category, @vehicle)%>
    <%= link_to "Accessories", admin_category_vehicle_accessories_path(@vehicle.category, @vehicle)%>
    <%= link_to "VehicleSlider", admin_category_vehicle_slider_path(@vehicle.category, @vehicle)%>
    <%= link_to "VehicleDMFile", admin_category_vehicle_dm_path(@vehicle.category, @vehicle)%>
    <%= link_to "VehiclePhotoGallery", admin_category_vehicle_photo_path(@vehicle.category, @vehicle)%>
  </nav>
</header>

<% if @gallery_count < 5 %>
  <%= simple_form_for(@vehicle, :url => admin_category_vehicle_upload_slider_path(params[:category_id] , @vehicle), html: { id: "patchthisvehicle", :multipart => true } ) do |f| %>

    <%= render 'admin/common/upload_by_type', target_title: '圖片' %>
    
    <%= f.hidden_field :status, :value => 'enable' %>

    <%= f.submit 'Save' %><br>

  <% end %>
  
<% end %>

<%= render 'admin/common/show_by_type', target: @vehicle, target_title: '圖片', type: 'VehicleSlider' %>

<%= link_to "返回", admin_category_path(@vehicle.category) %>