config/routes.rb
Rails.application.routes.draw do
  
  resources :announcements, only: [:index, :show]
  resources :banners, only: [:index, :show]

  devise_for :admins
  
  root "statics#index"
  
  get "/ebike/index.php" => redirect("http://ebike.citypower.com.tw/regist.php")

  resources :pages, :controller => :statics, only: [:index, :show, :vehicles] do 
    collection do
      get "vehicles" => "statics#vehicles", :as => "vehicles"
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :vehicles, only: [:index, :show]
  
  resources :stations, only: [:index, :show] do 
    collection do 
      post 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stations#fetch_from_country'
  get 'fetch_from_city' => 'stations#fetch_from_city'

  resources :contacts, only: [:index, :create]
  # resources :reservations, only: [:index, :create]

  resources :FAQs, :controller => :boxes , :only => [ :index, :show] # resources :boxes, only: [:index, :show]
  
  resources :faqs, only: [:fetch_by_box] do
    collection do 
      match 'search' => 'faqs#search', via: [:post], as: :search  
    end
    member do
      get 'fetch_by_box', action: 'fetch_by_box'
    end
  end

  # Admin
  namespace :admin do

    authenticated :admin do
      root "announcements#index"#, :as => :authenticated_root
    end
    
    resources :admins

    resources :announcements do 
      member do
        post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
        match :announcementphoto_upload, :via => :get

        get '/custom_edit' => 'announcements#custom_edit'
        patch '/custom_edit' => 'announcements#update'

      end
    end
    
    resources :index_sliders, controller: 'banners', type: 'IndexSlider'
    resources :selected_vehicles, controller: 'banners', type: 'SelectedVehicle'
    
    #BES Stations
    resources :stations do
      member do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'

        post 'create_station_attachment' , :action => 'create_station_attachment'
        match :stationphoto_upload, :via => :get
      end 

      collection do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'
      end
    end

    resources :categories do 
      resources :vehicles do

        get   '/sliders'       => 'vehicles#slider', as: 'slider'
        patch  '/upload_slider'       => 'vehicles#upload_slider'

        get   '/dms'       => 'vehicles#dm', as: 'dm'
        patch  '/upload_dm'       => 'vehicles#upload_dm'

        get   '/photos'       => 'vehicles#photo', as: 'photo'
        patch  '/upload_photo'       => 'vehicles#upload_photo'

        resources :specs
        resources :accessories
        resources :features
        resources :colors

      end

      member do
        patch 'reorder' , :action => 'reorder'
      end 

    end

    resources :vehicles do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end
    
    resources :boxes do 
      resources :faqs do 
        member do 
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        end
      end 
    end

    resources :galleries do 
      member do
        patch 'multiple_reorder' , :action => 'multiple_reorder'
      end 
    end

    resources :contacts, :only => [:index, :update, :reset_status] do
      collection do 
        get 'history', action: 'history'
      end
      member do 
        put 'reset_status', action: 'reset_status'
        put 'soft_delete', action: 'soft_delete'
      end
    end
    
    resources :reservations, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end
    
  end

  get '(*url)'   => 'errors#index'

end

app/models/station.rb
#encoding: utf-8
class Station < ActiveRecord::Base
  # map
  # acts_as_mappable  :default_units => :kms, :default_formula => :sphere

  has_many :galleries, -> { order('ranking, created_at') } , as: :attachable , dependent: :destroy

  default_scope { order('city ASC, district ASC') }
  
  before_validation :check_attrs
  validates_presence_of :name 

  paginates_per 10

  def check_attrs
    self.name = "untitled" if self.name.blank?
  end
  
end

app/controllers/admin/stations_controller.rb
#encoding: utf-8
class Admin::StationsController < AdminController
  
  #helper_method :sort_column, :sort_direction
  
  before_action :set_station, only: [:show, :edit, :update, :destroy, :stationphoto_upload, :create_station_attachment]

  def index
    
    #<%= sort_link @q , :payment_type, "付款方式" %>
    @stations = Station.page(params[:page])
    #@station = Station.new
  end

  def new
    @station = Station.new

    @countries = Country.all #use it when country selectable
    @cities = City.where("country_id = ?", Country.first.id)
    @districts = District.where("city_id = ?", City.first.id)

  end
    
  def create

    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to edit_admin_station_path(@station), notice: 'station was successfully created.'}
      else
        format.html { redirect_to :back, notice: @station.errors.full_messages }
      end
    end

  end

  def show
    #.pluck(:name, :lat, :lng).to_json
    # nearby_info = Station.within(5, origin: @station)
    # @info_array = Array.new
    # nearby_info.each do |station|
      
    #   if station.galleries.select{ |v| v['type'] == "StationPhotoGallery"  }.first
    #     a = station.galleries.select{ |v| v['type'] == "StationPhotoGallery"  }.first.attachment.url 
    #   end

    #   temp = [render_to_string(partial: 'info_window', :layout => false, locals: {station: station})]
    #   @info_array.push(temp)
    # end 
    
  end

  # GET /admin/stations/1/edit
  def edit
    
    @cities = City.where("country_id = ?", @station.country)
    @districts = District.where("city_id = ?", @station.city)
    #get all tag by context
    #@all_tag_with_context = ActsAsTaggableOn::Tagging.where(:context => 'services').joins(:tag).select('DISTINCT tags.name').map{ |x| x.name}

  end

  # tab-2: station photo uploads
  def stationphoto_upload
    @gallery_count = @station.galleries.select{ |v| v['type'] == "StationPhotoGallery" }.count
  end

  def create_station_attachment
      #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@station.name}-STORE-#{@station.galleries.count + 1}"
    end
    @latestAttach = StationPhotoGallery.create(:attachment => params[:attachment], :attachable => @station, :file_name => display_name) if params[:attachment]
    
    respond_to do |format|
       format.html { redirect_to stationphoto_upload_admin_station_path(@station), notice: 'station photo was successfully created.' }
       #format.js {render :js => "window.location.href=window.location.href"}
    end
  end

  def fetch_from_country
    @cities = City.where("country_id = ?", params[:country_id])
    @districts = District.where("city_id = ?", @cities.first.id)
    respond_to do |format|
      format.js
    end    
  end

  def fetch_from_city 
    
    @districts = District.where("city_id = ?", params[:city_id])
    respond_to do |format|
      format.js
    end    
  end


  # PATCH/PUT /admin/stations/1
  # PATCH/PUT /admin/stations/1.json
  def update

    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to admin_stations_path(), notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: :back }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/stations/1
  # DELETE /admin/stations/1.json
  def destroy

    #也要處理相關tags的刪除？

    @station.destroy
    respond_to do |format|
      format.html { redirect_to admin_stations_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_station
    #@station = Station.friendly.find(params[:id])
    @station = Station.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def station_params
    params.require(:station).permit(:name, :address, :intro, :phone, :address, :country, :city, :district, :ophour, :latlng, :location_list , :lat, :lng  )
  end

  #change implementation to ransack
  # def sort_column
  #   Station.column_names.include?(params[:sort]) ? params[:sort] : "name"
  # end
  
  # def sort_direction
  #   %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  # end

end

app/controllers/stations_controller.rb
#encoding: utf-8
class StationsController < ApplicationController
  
  before_action :set_station, only: [:show]

  def index

    @countries = Country.all #use it when country selectable
    @cities = City.where("country_id = ?", Country.first.id)
    @districts = District.where("city_id = ?", City.first.id)

    @q = Station.search(params[:q])

  end

  def search
    
    @q = Station.search(params[:q])
    @stations = @q.result(distinct: true).includes(:galleries)

    if @stations.count <= 0
      
      if params[:q]['city_eq']
         target_city = City.where(id: params[:q]['city_eq'].to_i).limit(1).pluck(:name)
         @target_city_name = target_city[0] if target_city
      end

      if params[:q]['district_eq']
        target_district = District.where(id: params[:q]['district_eq'].to_i).limit(1).pluck(:name)
        @target_district_name = target_district[0] if target_district
      end

    end

    respond_to do |format|
      format.js
    end    
    
  end

  def show
    
  end

  def fetch_from_country
    @cities = City.where("country_id = ?", params[:country_id])
    @districts = District.where("city_id = ?", @cities.first.id)
    respond_to do |format|
      format.js
    end    
  end

  def fetch_from_city 
    
    @districts = District.where("city_id = ?", params[:city_id])
    respond_to do |format|
      format.js
    end    
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @station = Station.find(params[:id])
  end

end

app/views/admin/stations/_info_window.html.erb
<div class="info_content">
  <h3><%= station.name %></h3>
    <p><%= station.ophour %></p>
    <p><%= station.intro %></p>
    <% if station.galleries.select{ |v| v['type'] == "StationPhotoGallery"  }.first %>
      <%= image_tag station.galleries.select{ |v| v['type'] == "StationPhotoGallery"  }.first.attachment.url, width: '280px', height: 'auto'   %>
    <% end %>
</div>

app/views/admin/stations/edit.html.erb
<header>
  <h2 class="left">地圖管理</h2>
  <nav class="left">
    <a href="javascript:void(0);" class="active">簡介</a>
    <%= link_to "照片", stationphoto_upload_admin_station_path(@station)%>
  </nav>
</header>
<article>
  
    <%= form_for @station, :url => admin_station_path(@station), html: {method: "patch" , id: "patchthisstation"} do |f| %>
      <div class="form">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="9%">門市：</td>
            <td width="39%"><%= f.text_field :name , class: "text" %></td>
            <td width="4%"></td>
            <td width="9%">電話：</td>
            <td width="39%"><%= f.text_field :phone , class: "text" %></td>
          </tr>
          <tr>
            <td valign="center">地址：</td>
            <td colspan="4" >
              <%= f.hidden_field :country , value: 1 %>         
              <%= f.select :city, options_for_select(@cities.collect { |city|
                [city.name, city.id] }, @station.city), {}, { id: 'cities_select', style: 'width:150px' } %>
              <%= f.select :district, options_for_select(@districts.collect { |district|
                [district.name, district.id] }, @station.district), {}, { id: 'districts_select', style: 'width:150px' } %><br>
                <%= f.text_field :address ,class: "text", placeholder:"請輸入完整地址"%>
            </td>
          </tr>
          <tr>
            <td valign="top">地圖：</td>
            <td colspan="4"><%= f.text_field :latlng,class: "text" %> </td>
          </tr>
          <!-- <tr> -->
            <!-- <td>緯度(Latitude)：</td> -->
            <!-- <td colspan="4"><%# f.text_field :lat,class: "text" %> </td> -->
          <!-- </tr> -->
          <!-- <tr> -->
            <!-- <td>經度(Longitude)：</td> -->
            <!-- <td colspan="4"><%# f.text_field :lng,class: "text" %> </td> -->
          <!-- </tr> -->
        </table>
      </div>
    <% end %>
  
  <!--form-->

  <div class="button"> 
    <%= link_to image_tag("/images/admin/left.png")+"返回", admin_stations_path(), class: "left" %>
    <a href="javascript: document.getElementById('patchthisstation').submit();" class="right highlight" data-no-turbolink = true >儲存<img src="<%= image_path("/images/admin/save.png") %>"></a>
  </div>
  
</article>

<script type="text/javascript">

</script>

app/views/admin/stations/index.html.erb
<header>
  <h2 class="left">地圖管理</h2>
</header>
<article>
  <div class="hgroup">
    <div class="button">
      <%= link_to new_admin_station_path(), :method => :get,class: "right highlight"  do %>
        新增站點<img src="/images/admin/add.png">
      <% end %>
    </div>
  </div>
  <div class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <% @stations.each do |station| %>
        <tr>
          <td width="6%" class="icon"><img src="/images/admin/li.png"></td>
          <td width="76%"><%= link_to "#{station.name}", edit_admin_station_path(station) %></td>
          <td width="18%">
          <div class="tool">                
            <%= link_to "", edit_admin_station_path(station), class: "edit" %>
            <%= link_to "", admin_station_path(station), :data => { :confirm => "將會刪除此站點，確定繼續？" }, :method => :delete, :class => "delete", title: "刪除" %>
          </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class= "page">
    <%= paginate @stations ,:window => 2 %>
  </div>
</article>

app/views/admin/stations/new.html.erb
<header>
  <h2 class="left">地圖管理</h2>
  <nav class="left">
    <a href="javascript:void(0);" class="active">簡介</a>
    <%# link_to "照片", stationphoto_upload_admin_station_path(@station)%>
  </nav>
</header>
<article>
  <div class="form">
    <%= form_for @station, :url => admin_stations_path(@station), html: { id: "create_this_station",method: "post"} do |f| %>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="7%">門市：</td>
        <td width="42%"><%= f.text_field :name , class: "text" %></td>
        <td width="2%"></td>
        <td width="7%">電話：</td>
        <td width="42%"><%= f.text_field :phone , class: "text" %></td>
      </tr>
      <tr>
        <td valign="top" style="padding:13px 0 0 0">地址：</td>
        <td colspan="4">
            <%= f.select :country, options_for_select(@countries.collect { |country|
        [country.name, country.id] }, 1), {}, { id: 'countries_select', style: "width:14%;display:none;" } %>
            <%= f.select :city, options_for_select(@cities.collect { |city|
              [city.name, city.id] }, 1), {}, { id: 'cities_select', style: "width:14%" } %>
            <%= f.select :district, options_for_select(@districts.collect { |district|
              [district.name, district.id] }, 0), {}, { id: 'districts_select' , style: "width:14%"} %>

          <%# f.hidden_field :country , value: 1 %>   

          <%# f.select :city, options_for_select(@cities.collect { |city|
            [city.name, city.id] }, @station.city), {}, { id: 'cities_select', style: "width:14%" } %>
          <%# f.select :district, options_for_select(@districts.collect { |district|
            [district.name, district.id] }, @station.district), {}, { id: 'districts_select', style: "width:14%" } %><br>
            <%= f.text_field :address ,class: "text", placeholder:"請輸入完整地址"%>
          </td>
      </tr>
      <tr>
        <td>地圖：</td>
        <td colspan="4"><%= f.text_field :latlng,class: "text" %> </td>
      </tr>
    </table>
    <% end %>
  </div>
  <!--form-->

  <div class="button"> 
    <%= link_to image_tag("/images/admin/left.png")+"返回", admin_stations_path(), class: "left" %>
    <a href="javascript: document.getElementById('create_this_station').submit();" class="right highlight" data-no-turbolink = true >儲存<img src="<%= image_path("/images/admin/save.png") %>"></a>
  </div>
  
</article>

app/views/admin/stations/show.html.erb
Store show<br>
<p id='status'></p>

<%= @station.name %><br>
<%= @station.intro %><br>
<%= @station.phone %><br>
<%= @station.address %><br>
<%= @station.ophour %><br>
<%= @station.latlng.html_safe %><br>
<%= @station.lat %> , <%= @station.lng %><br>
<% if @station.galleries.select{ |v| v['type'] == "StationPhotoGallery"  }.first %>
    <% a = @station.galleries.select{ |v| v['type'] == "StationPhotoGallery"  }.first.attachment.url  %>
<% end %>


<br><br><br><br>
<%= link_to "GO BACK", admin_stations_path %>

app/views/admin/stations/stationphoto_upload.html.erb
<style>
div ,td, p .noTransition {
    -moz-transition: none;
    -webkit-transition: none;
    -o-transition: color 0 ease-in;
    transition: none;
}
</style>
<header>
  <h2 class="left">地圖管理</h2>  
  <nav class="left">
    <%= link_to "簡介", edit_admin_station_path(@station)%>
    <a href="javascript:void(0);" class="active">照片</a>
  </nav>
</header>
<article>

  <% if @gallery_count < 5 %>

  <div class="form">
    <%= form_for(@station,url: create_station_attachment_admin_station_path(@station) , :html => {:id =>'NewAttachlForm' , :method => "POST", :multipart => true} ) do |fattach| %>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="7%">圖片：</td>
          <td width="93%"><%= file_field_tag :attachment , class: 'file' %></td>
        </tr>
      </table>
   <% end %>  
  </div>

  <div class="button">
    <a href="javascript: document.getElementById('NewAttachlForm').submit();" class="right highlight" data-no-turbolink = true >上傳
      <img src="<%= image_path("/images/admin/up.png") %>">
    </a>
  </div>
  
  <% end %>
  <div class="hgroup">
    <h3 class="left">圖片預覽<span>(可拖拉排序，第一張為封面)</span></h3>          
  </div>
  <div class="gallery" id="listThisAttach">

    <% @station.galleries.select{ |v| v['type'] == "StationPhotoGallery" }.each_with_index do |attach, i| %>
      <% if i == 0 %>
        <div class="thumb left cover createAttachcontainer dragable" <%= "id=createAttachcontainer_#{attach.id.to_s}" %>> 
      <% else %>
        <div class="thumb left createAttachcontainer dragable" <%= "id=createAttachcontainer_#{attach.id.to_s}" %>> 
      <% end %>
      
        <%= link_to '', admin_gallery_path(attach.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete', title: '刪除' %>
        <image src=<%= "#{attach.attachment.url}" %> />
      </div>
    <% end %>

  </div>
</article>

<script>
$(function() {
  var prevEvent = null;
    $( "#listThisAttach" ).sortable({
      //connectWith: ".renamelevelcontainer",
      items: "> .dragable" ,
      placeholder: "ui-state-highlight",
      update: function( event, ui ) {
          
      if(event.timeStamp == prevEvent){
        return null;
      }
      
      prevEvent = event.timeStamp;  
      var newRankings_array = $('#listThisAttach').sortable('toArray');
      var orderSet = [];
      $.each(newRankings_array, function( index, value){
            orderSet.push(value.replace("createAttachcontainer_",""));
        });
        var order2Push = JSON.stringify(orderSet);
        
        $.ajaxSetup({
          headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
      });

          //multiple reorder 
          $.ajax({
            type: "PATCH",
            url: "/admin/galleries/"+orderSet[0]+"/multiple_reorder",
            data: { gallerries: {  reorderset: orderSet } },
            success: function(data){

              $("#listThisAttach > .thumb").attr('class', 'thumb left createAttachcontainer dragable');
              $("#listThisAttach > .thumb:first").attr('class', 'cover thumb left createAttachcontainer dragable');
              alertify['success'](data[0][1], 2000);
              //console.log("================ stations reorder PATCH successfully end =============");
              return false   
            },
            error: function(data){
            //alert ("faild");
              //console.log("================ stations reorder has some issues ==================");
              return false  
            }
          });

      }
    });
    
      
    $( "#listThisAttach" ).disableSelection();
  });  
//################################ attachment reorder end #######################################
</script>