config/routes.rb
Rails.application.routes.draw do
  
  resources :announcements, only: [:index, :show]
  resources :banners, only: [:index, :show]

  devise_for :admins
  
  root "statics#index"
  
  get "/ebike/index.php" => redirect("http://ebike.citypower.com.tw/regist.php")

  resources :pages, :controller => :statics, only: [:index, :show, :vehicles] do 
    collection do
      get "vehicles" => "statics#vehicles", :as => "vehicles"
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :vehicles, only: [:index, :show]
  
  resources :stations, only: [:index, :show] do 
    collection do 
      post 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stations#fetch_from_country'
  get 'fetch_from_city' => 'stations#fetch_from_city'

  resources :contacts, only: [:index, :create]
  # resources :reservations, only: [:index, :create]

  resources :FAQs, :controller => :boxes , :only => [ :index, :show] # resources :boxes, only: [:index, :show]
  
  resources :faqs, only: [:fetch_by_box] do
    collection do 
      match 'search' => 'faqs#search', via: [:post], as: :search  
    end
    member do
      get 'fetch_by_box', action: 'fetch_by_box'
    end
  end

  # Admin
  namespace :admin do

    authenticated :admin do
      root "announcements#index"#, :as => :authenticated_root
    end
    
    resources :admins

    resources :announcements do 
      member do
        post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
        match :announcementphoto_upload, :via => :get

        get '/custom_edit' => 'announcements#custom_edit'
        patch '/custom_edit' => 'announcements#update'

      end
    end
    
    resources :index_sliders, controller: 'banners', type: 'IndexSlider'
    resources :selected_vehicles, controller: 'banners', type: 'SelectedVehicle'
    
    #BES Stations
    resources :stations do
      member do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'

        post 'create_station_attachment' , :action => 'create_station_attachment'
        match :stationphoto_upload, :via => :get
      end 

      collection do 
        get 'fetch_from_country' , action: 'fetch_from_country'
        get 'fetch_from_city' , action: 'fetch_from_city'
      end
    end

    resources :categories do 
      resources :vehicles do

        get   '/sliders'       => 'vehicles#slider', as: 'slider'
        patch  '/upload_slider'       => 'vehicles#upload_slider'

        get   '/dms'       => 'vehicles#dm', as: 'dm'
        patch  '/upload_dm'       => 'vehicles#upload_dm'

        get   '/photos'       => 'vehicles#photo', as: 'photo'
        patch  '/upload_photo'       => 'vehicles#upload_photo'

        resources :specs
        resources :accessories
        resources :features
        resources :colors

      end

      member do
        patch 'reorder' , :action => 'reorder'
      end 

    end

    resources :vehicles do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end
    
    resources :boxes do 
      resources :faqs do 
        member do 
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
        end
      end 
    end

    resources :galleries do 
      member do
        patch 'multiple_reorder' , :action => 'multiple_reorder'
      end 
    end

    resources :contacts, :only => [:index, :update, :reset_status] do
      collection do 
        get 'history', action: 'history'
      end
      member do 
        put 'reset_status', action: 'reset_status'
        put 'soft_delete', action: 'soft_delete'
      end
    end
    
    resources :reservations, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end
    
  end

  get '(*url)'   => 'errors#index'

end

app/controllers/statics_controller.rb
#encoding: utf-8
class StaticsController < ApplicationController

  def index
    @announcements = Announcement.includes(:galleries).for_index.limit(3)
    @banners = Banner.sliders.includes(:galleries).where(status: 'enable').limit(5)
    products_ids = Banner.vehicles.where(status: 'enable').distinct.limit(3).pluck(:related_product_id)
    @pickups = Vehicle.includes(:galleries).where(id: products_ids, status: 'enable')
  end

  def about

  end

  def vehicles
    @categories = Category.includes(:vehicles).where(depth: 1)
  end

  def show
  
    if params[ :page ].nil?
      redirect_to :index
    end
    
    respond_to do | format |
      format.html { render :template => 'statics/' + params[ :page ]  rescue redirect_to '/errors' }
    end
    
  end

end

app/views/statics/about.html.erb
<link href="/css/about.css" rel="stylesheet" type="text/css">
<!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="/css/ie8.css" />
<![endif]-->

<article>
	<div class="banner">
    <div class="container">
    	<h1>認識城市動力</h1>
    </div>    
    </div>
    
    <div id="crumb">
        <section class="container" >
          <ol class="breadcrumb">
            <li><%= link_to "首頁", root_path %></li>
            <li class="active">認識城市動力</li>
          </ol>
        </section>
    </div>
    
    <section class="about">
    <div class="container">
        <img id="aboutImg" src="/images/img_about.jpg">
        <div id="about01">
        <h1>台灣城市動力</h1>
        <h2>CITY POWER</h2>
        <p>城市動力致力電動機車產業發展，使之形成為國家政策，首先電池交換系統 (BES ) 獲得行政院環保署認可，於新北市首先設站，並保障 5000 輛車子每輛補助 10000 元交換費用，2013 年底城市動力系統更進一步成為全國的共通規格系統，2014 年初又促成行政院環保署擴大補助範圍至電動自行車；同時間，城市動力也期許成為消費者最可靠的電動機車專家，任何交換型電動機車相關疑難雜症，交給城市動力就對了；預計 2014 年底前 10 個公司直營服務中心也將在新北市各區成立，目前已完成中和及蘆洲兩區服務中心。
</p>
        </div>
      <div id="about02">
          <img id="mark1" src="/images/bes-01.jpg" width="30" height="30">
          <img id="mark2" src="/images/bes-03.jpg" width="30" height="30">
<p>另一重大成就為公共 EBIKE 的設立，我們相信，電動二輪車的公共化會是改變這個社會交通現象的重大政策，公共 EBIKE 設立將有助於電池交換站之設置，而 BES 站的普及將更能加強民眾對對電動機車的認同。</p>
            <p>城市動力這幾年努力的方向是大格局的，如:建立 BES 系統平台、制訂共通電池規格、協調推動政策制訂法案、擬訂各項獎勵補助法令(如:補助車廠開發及檢測費用 65 至 300 萬、補助民眾購車及交換電池費用 11000 至 20000 元、補助各地方政府推動電動化政策等)，這些努力成果看似平常卻內含諸多龐大效益，如降低廠商投資開發風險協助產業發展，降低民眾購車負擔以增加銷售量，達到電動機車普及的目的；這些都大大提升城市動力的社會價值。</p>
      </div>
    </div>
    </section>
    
    <section class="road">
    <div class="container">
    	<div id="road01">
        <h1>城市動力在走一條<br>不一樣的路</h1>
        <p>城市動力橫跨能源 ( 直流電力及動力電池 )、環保 ( 電動機車 )、銷售通路 ( 直營服務中心及全國 3C 連鎖店 ) 及服務平台 ( 電池交換站 )，是行業的絕對領導者。</p>
        </div>
        <div class="row">
        <div class="col-xs-6 col-sm-3">
          <div id="r01">建構電池交換站服務平台開賣直流電力有如當年的中油公司</div>         
        </div>
        <div class="col-xs-6 col-sm-3">
          <div id="r02">制訂電動二輪車共通規格成為全國最大動力電池組供應商</div>
        </div>
        <div class="col-xs-6 col-sm-3">
          <div id="r03">致力於環保產業電動二輪車的開發，目前符合國家標準的車款城市動力佔了50%以上</div>
        </div>
        <div class="col-xs-6 col-sm-3">
          <div id="r04">電動機車行業最大銷售通路管道基本形成，僅新北市就超過五十個</div>
        </div>
      </div>
    </div>
    </section>
    
    <section class="event">
    <div class="container">
    	<h1>城市動力大事記</h1>
        <div id="event">
            <div id="e01">
            <table class="table">
              <tr>
                <td>2014</td>
                <td class="eventTxt">電池交換系統正式啟動<br><br></td>
              </tr>
              <tr>
                <td>2010</td>
                <td class="eventTxt">成立台灣城市動力股份有限公司<br><br></td>
              </tr>
              <tr>
                <td>2009</td>
                <td class="eventTxt">開發完成第三代鋰電池電動摩托車交換系統<span>並著手在台運行。</span></td>
              </tr>
            </table>
            </div>
            <div id="e02">
           <table class="table">
              <tr>
                <td>2008</td>
                <td class="eventTxt">全力轉型開發電動摩托車鋰電池交換系統。<br><br></td>
              </tr>
              <tr>
                <td>2006</td>
                <td class="eventTxt">原生產設備讓與中方持續運營。<br><br></td>
              </tr>
              <tr>
                <td>2003</td>
                <td class="eventTxt">蘇州電動(自行)車電池交換系統正式營運<span>兩個月內銷售近五千輛。</span></td>
              </tr>
            </table>
            </div>
            <div id="e03">
            <table class="table">
              <tr>
                <td>2002</td>
                <td class="eventTxt">於蘇州成立分公司，設立電動(自行)車廠及<span>28個電池交換站。</span></td>
              </tr>
              <tr>
                <td>2000</td>
                <td class="eventTxt">於中國廣州成立萬易通能源科技股份有限公司，<span>專事動力鎳氫電池及電池交換系統。</span></td>
              </tr>
              <tr>
                <td>1998</td>
                <td class="eventTxt">為長榮集團所併購，更名為長榮能源科技股份有限公司。<br><br></td>
              </tr>
            </table>
            </div>
            <div id="e04">
            <table class="table">
              <tr>
                <td>1996</td>
                <td class="eventTxt">於中國江蘇太倉成立億威能源科技股份有限公司。<br><br></td>
              </tr>
              <tr>
                <td>1994</td>
                <td class="eventTxt">退出台達節能股份有限公司，成立專門鎳氫電池整<span>廠設備製造，準備進軍中國市場。</span></td>
              </tr>
              <tr>
                <td>1989</td>
                <td class="eventTxt">為台達電子股份有限公司併購，更名為台達節能股份<span>有限公司。</span></td>
              </tr>
            </table>
            </div>
            <div id="e05">
            <table class="table">
              <tr>
                <td>1987</td>
                <td class="eventTxt">與洪博士成立聯合能源科技股份有限公司從事鎳氫<span>電池的開發生產。</span></td>
              </tr>
              <tr>
                <td>1986</td>
                <td class="eventTxt">中國國務院編列十億人民幣預算作鎳氫電池的研究<span>開發及生產。</span></td>
              </tr>
              <tr>
                <td>1985</td>
                <td class="eventTxt">中國派遣六批共二百餘科技人員至美國接受洪國治<span>博士訓練。</span></td>
              </tr>
              <tr>
                <td>1984</td>
                <td class="eventTxt">旅美洪國治博士於北京國際氫能源會議發表儲氫<span>材料論文，開啟了國際鎳氫電池商品化熱潮。</span></td>
              </tr>
            </table>
            </div>
            
        </div>
    </div>
    </section>
</article>

app/views/statics/app.html.erb
<link href="/css/app.css" rel="stylesheet" type="text/css">


<article>
	<div class="banner">
    <div class="container">
    	<h1>App介紹</h1>
    </div>    
    </div>
    
    <div id="crumb">
        <section class="container" >
          <ol class="breadcrumb">
            <li><%= link_to "首頁", root_path %></li>
            <li class="active">App介紹</li>
          </ol>
        </section>
    </div>
    
    <section class="app">
    <div class="container">
       <h1>APP介紹</h1>
       <div id="app01"><img src="/images/idx-07.jpg"></div>
       <div id="app02">
       	 <div class="intro">
         <h2>1. 站點地圖查詢</h2>
		 <p>配合 google map，可輕易的看出您附近之站點與電池數量．在點選欲到達之站點後（<span>紅框</span>處顯示資料），還可利用 google map 導航功能，設定路線．<span id="highlight">即便沒有網路，也可以做離線查詢．</span></p>
         <img src="/images/img_app01.jpg">
         <img src="/images/img_app02.jpg">
         <img src="/images/img_app03.jpg">
         </div>
         <div class="intro">
         <h2>2. 站點地區查詢</h2>
		 <p>可依據需求區域查詢站點（<span>紅框</span>處設定區域），會以清單方式列出站點位置</p>
         <img src="/images/img_app04.jpg">
         <img src="/images/img_app05.jpg">
		 </div>
         <div class="intro">
         <h2>3. 線上故障通報</h2>
		 <p>可於線上通報欄位直接輸入問題，線上客服人員將會立即處理您的問題
也可以直接播打客服專線或以 email 聯絡</p>
		 <img src="/images/img_app06.jpg">
		 </div>
         <div id="download">
         <h2>App 下載專區</h2>
		 <span>請選擇與您裝置相符的版本下載</span>
          <p>
            <a href="https://play.google.com/store/apps/details?id=bes.example.mo" target="_blank" title="前往下載"><img src="/images/img_app_android.gif" width="170" height="51"></a>
            <img class="qrcode" src="/images/img_app_android2.gif" width="142" height="142">
          </p>
          <!--<p>
            <a href="#" title="App Store"><img src="/images/img_app_ios.gif" width="170" height="51"></a><img class="qrcode" src="/images/img_app_android2.gif" width="142" height="142">
          </p>-->
         </div>
       </div>
    </div>
    </section>
</article>

app/views/statics/comingsoon.erb
<link rel="stylesheet/less" type="text/css" href="/css/global.less" />
<style>header{background:#000;}</style>

<article>
  <img src="/images/cs.jpg" class="img-responsive">
</article>

app/views/statics/index.html.erb
<link rel="stylesheet" type="text/css" href="/js_plugins/bxslider/jquery.bxslider.css" />
<link rel="stylesheet/less" type="text/css" href="/css/index.less" />
<!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="/css/index.css" />
    <link rel="stylesheet" type="text/css" href="/css/ie8.css" />
<![endif]-->

<script src="/js_plugins/bxslider/jquery.bxslider.min.js"></script> 
<script src="/js/less.min.js"></script>
<script>
  $(document).ready(function(){
    $('.bxslider').bxSlider({
      controls:false,
      auto:true,
      mode:'fade',
    });
  });    
</script>
</head>

<body>


<div id="slider">
  <ul class="bxslider">
    <% @banners.each do |banner| %>
      <% if banner.galleries.first %>
        <li>
          <%= link_to banner.description, target: '_blank' do %>
            <img src=<%= "#{banner.galleries.first.attachment.url}" %> class="img-responsive" />
          <% end %>
        </li>
       <% end %>
    <% end %>
  </ul>
</div>
<article class="index">  
  <div id="content-1" class="content">
    <section class="container row">
      <h3 class="col-sm-12">最新消息</h3>
      
      <%  if @announcements.count >= 1  %>
        <% @announcements.each do |announcement| %>
          <div class="col-sm-3">
            <%= link_to announcement_path(announcement), class: 'news' do %>
            
              <div class="cover">
                <% if announcement.galleries.select{ |v| v['type'] == "AnnouncementCoverGallery" }.first %>
                <% announcement_cover_url = announcement.galleries.select{ |v| v['type'] == "AnnouncementCoverGallery" }.first.attachment.url %>
                  <%= image_tag announcement_cover_url , class: "img-responsive" if announcement_cover_url %>
                <% end %>
                <div class="mask hidden-sm hidden-xs">
                  <span class="date"><%= announcement.created_at.strftime('%m/%d') %></span><br>
                  <p>
                    <% if announcement.subtitle %>
                      <%= announcement.subtitle.first(23) if announcement.subtitle.length > 0 %>
                      <%= '...' if announcement.subtitle.length > 23 %>
                    <% end %>
                  </p>
                </div>
              </div>
              <div class="title">
                <%= announcement.title %><br><br>
              </div>

            <% end %>
          </div>
        <% end %>
      <% end %>
      
      <div class="col-sm-3">
        <%= link_to announcements_path, class: "more" do %>
          <img src="/images/idx-01.gif" class="img-responsive"/>
        <% end %>
      </div>

    </section>
  </div>
  <div id="content-2" class="content">
    <section class="container">
      <h1>綠色環保 電動機車</h1>
      <h2>降低摩托車一氧化碳的排放，減少對環境的污染</h2>
      <div class="row list">
      <% @pickups.each do |vehicle| %>
        <%= link_to vehicle_path(vehicle), {:class=>"col-md-4"} do %>
            <%= render 'layouts/show_by_type', target: vehicle, target_title: '', type: 'VehicleCover' %>
            <hr>
            <h4><%= vehicle.name %></h4>
            <h5><%= vehicle.description %></h5>
            <button class="btn btn-default"><span>看更多</span></button>
        <% end %>
      <% end %>
      </div>
    </section>
  </div>
  <div id="content-3" class="content">
    <section class="container clearfix">      
      <div class="pull-right">
        <h3>認識 BES 電池交換站<br><small>/ Battery Exchange System</small></h3>       
          <div id="rope">
          <div id="box">
          <h4><img src="/images/idx-08.png"> 電池交換站</h4>
          <p>再也不用擔心電動機車騎到一半沒電啦，到電池交換站換一顆充飽電的電池，城市動力將能滿足您最及時的需求。</p>
          <br>
          <h4><img src="/images/idx-08.png"> 永久保固</h4>
          <p>有了電池交換站，您的車上的電池將能享受城市動力的永久保固，不僅能隨時至交換站換取良好的電池，也不需要每隔兩三年付出2~3 萬的更換電池費用啦。</p>
          <br>
          <h4><img src="/images/idx-08.png"> 站點位置</h4>
          <p>站點將設置於民眾最熟悉的地方體育館，停車場，公園，市場，乃至路邊的停車格等等．務必讓民眾享受到最貼心的服務。</p>
          </div>
          </div>
      </div>
      <div class="pull-left">
        <img src="/images/idx-04.png" class="img-responsive">
      </div>
    </section>
  </div>
  <div id="content-4" class="content">
    <section class="container clearfix">      
      <div class="pull-left">
        <h3>BES 電池交換站 App 介紹</h3>       
          <h4>隨時查詢站點</h4>
          <p>可依據地圖，地區二種方式查詢站點，即使離線也能查詢，不必擔心找不到交換站</p>
          <h4>線上客服支援</h4>
          <p>有任何問題可隨時以線上客服回覆，有關電動機車的任何問題，找城市動力就對了</p>
          <div class="qrcode hidden-sm hidden-xs">
            <br>
            <a href="https://play.google.com/store/apps/details?id=bes.example.mo" target="_blank" title="前往下載"><img src="/images/idx-12.png"></a>
          </div>
          <div class="more">
            <%= link_to "詳細介紹 >", page_pages_path('app')%>
          </div>          
      </div>
      <div class="pull-right">
        <img src="/images/idx-07.jpg" class="">
      </div>
    </section>
  </div>
  <div id="content-5" class="content">
    <section class="container clearfix">      
      <div class="pull-left">
        <h3>E-BIKE 介紹</h3>       
          <h4>電動二輪車公共化</h4>
            <ul>
              <li>「行政院環保署電動二輪車免費試運行」</li>
              <li>不知何時腳踏車租借變成一種潮流，現在，該騎電動自行車啦。</li>
              <li>路邊停車柱停著電動二輪載具，到租借機刷悠遊卡，即可隨時租用電動自行車四處遨遊。</li>
            </ul>          
        <div class="more">
          <a href="http://ebike.citypower.com.tw" target="_blank">更多 E-bike 介紹 ></a>
        </div>     
        <div class="stick">
          <img src="/images/idx-11.png">
        </div>
        <img src="/images/idx-09.png" id="mMoto" class="img-responsive hidden-sm hidden-md hidden-lg">
      </div>
    </section>
  </div>
</article>

app/views/statics/processes.html.erb
<link rel="stylesheet/less" type="text/css" href="/css/processes.less" />
<!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="/css/processes.css" />
    <link rel="stylesheet" type="text/css" href="/css/ie8.css" />
<![endif]-->

<article>
  <div class="banner">
    <div class="container">
      <h1>BES 電池交換系統</h1>
      <h2>/ Battery Exchange System</h2>
    </div>    
  </div>
    
    <div id="crumb">
        <section class="container" >
          <ol class="breadcrumb">
            <li><%= link_to "首頁", root_path %></li>
            <li class="active">認識 BES</li>
            <li class="active">BES 操作流程</li>
          </ol>
        </section>
    </div>
  <div class="content" id="content-1">
    <section class="container">
      <h3>BES 電池交換站操作流程步驟</h3>
      <div class="clearfix">
      <div class="step pull-left" id="step-1">
        <img src="/images/prc-01.jpg" class="img-responsive">
        <p>騎乘電動機車到交換站</p>
      </div>
      <div class="step pull-right" id="step-2">
        <img src="/images/prc-02.jpg" class="img-responsive">
        <p>將ID卡置於感應區</p>
      </div>
      </div>
      <div class="clearfix">
      <div class="step pull-left" id="step-3">
        <img src="/images/prc-03.jpg" class="img-responsive">
        <p>交換站吐出空軌</p>
      </div>
      <div class="step pull-right" id="step-4">
        <img src="/images/prc-04.jpg" class="img-responsive">
        <p>至車中取出電池</p>
      </div>
      </div>
      <div class="clearfix">
      <div class="step pull-left" id="step-5">
        <img src="/images/prc-05.jpg" class="img-responsive">
        <p>放入空軌中<br>系統同時確認電池資料</p>
      </div>
      <div class="step pull-right" id="step-6">
        <img src="/images/prc-06.jpg" class="img-responsive">
        <p>辨識完成後吐出一飽電之電池</p>
      </div>
      </div>
      <div class="clearfix">
      <div class="step pull-left" id="step-7">
        <img src="/images/prc-07.jpg" class="img-responsive">
        <p>取出電池置回車中</p>
      </div>
      <div class="step pull-right" id="step-8">
        <img src="/images/prc-08.jpg" class="img-responsive">
        <p>發動車輛享受您的旅程</p>
      </div>
      </div>
    </section>
  </div>
  <div class="content" id="content-2">
    <section class="container" >
      <h3>BES 電池交換站操作流程影片</h3>
      <!-- 4:3 aspect ratio --> 
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="embed-responsive embed-responsive-4by3">
            <iframe class="embed-responsive-item" src="//www.youtube.com/embed/lCYLzHfFp7M?rel=0"></iframe>
          </div>
        </div>
      </div>
    </section>
  </div>
</article>

app/views/statics/vehicles.html.erb
<link href="/css/list.css" rel="stylesheet" type="text/css">
<!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="/css/ie8.css" />
<![endif]-->

<article>
  <div class="banner">
    <div class="container">
      <h1>電動機車車款介紹</h1>
    </div>    
    </div>
    
    <div id="crumb">
        <section class="container" >
          <ol class="breadcrumb">
            <li><%= link_to "首頁", root_path %></li>
            <li class="active">車款介紹</li>
          </ol>
        </section>
    </div>
    
    <section class="list">
    <div class="container">
        <h1>BES 電動機車 / <span>車款介紹</span></h1>
      <% @categories.each do |category| %> 
        <div class="row">
        <h2><%= category.name %></h2>
        <% vehicleIndex=1 %>
        <% category.vehicles.where(status: 'enable').limit(6).each do |vehicle| %> 
            <%if vehicleIndex%4==0 %>
              <hr>
            <% end %>
            <%= link_to vehicle_path(vehicle), {:class=>"col-md-4"} do %>
                <%= render 'layouts/show_by_type', target: vehicle, target_title: '', type: 'VehicleCover' %>
                <hr>
                <h3><%= vehicle.name %></h3>
                <h4><%= vehicle.description %></h4>
                <button class="btn btn-default"><span>看更多</span></button>
            <% end %>
            
            <% vehicleIndex=vehicleIndex+1 %>
        <% end %>
        </div>    
    <% end %>  
  </div>
  </section>
</article>